<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { RouterLink, useRoute } from 'vue-router'
import { checkoutCart, getPaymentMethods, getOrderTracking, removeCartItem, updateCartItem, type Cart, type Order, type PaymentMethod } from '../lib/cart'
import { useCartState } from '../lib/cart-state'
import { getStorefront } from '../lib/storefront'

const route = useRoute()
const storeSlug = String(route.params.storeSlug)
const cartState = useCartState()
const cart = ref<Cart | null>(cartState.cart.value)
const order = ref<Order | null>(null)
const storeName = ref('')
const paymentMethods = ref<PaymentMethod[]>([])
const selectedPaymentMethod = ref('')
const checkoutStep = ref<'cart' | 'shipping' | 'payment'>('cart')
const loading = ref(!cart.value)
const loadingPaymentMethods = ref(true)
const submitting = ref(false)
const busyItems = ref<Record<string, boolean>>({})
const error = ref('')
const fieldError = ref('')
const form = reactive({ first_name: '', last_name: '', phone: '', email: '', notes: '' })
const itemCountLabel = computed(() => { const count = cart.value?.item_count || 0; return `${count} ${count === 1 ? 'item' : 'items'}` })
const trackingPath = computed(() => { if (!order.value?.tracking_url) return ''; try { return new URL(order.value.tracking_url, window.location.origin).pathname } catch { return '' } })
const selectedMethod = computed(() => paymentMethods.value.find(method => method.public_id === selectedPaymentMethod.value) || null)
const paymentMessage = computed(() => { if (!order.value?.payment) return ''; const payment = order.value.payment; if (payment.status === 'paid') return 'Payment received. Your order has been placed successfully.'; if (payment.status === 'processing' && payment.method.payment_type === 'stk_push') return `M-Pesa prompt sent to ${order.value.customer_phone}. Check your phone and enter your M-Pesa PIN to complete payment.`; if (payment.status === 'pending' && payment.method.code === 'cash') return 'Pay in cash when your order is delivered or collected.'; if (payment.status === 'pending' && payment.method.code === 'mpesa_paybill') return 'Complete the M-Pesa payment using the instructions shown for this order.'; if (payment.status === 'pending' && payment.method.code === 'card') return 'Your order is reserved. Complete the card payment through the configured card provider or terminal.'; if (payment.status === 'failed') return payment.failure_reason || 'The selected payment could not be completed.'; return 'Your payment is awaiting confirmation.' })
function money(minor: number, currency: string) { return new Intl.NumberFormat('en-KE', { style: 'currency', currency, maximumFractionDigits: 2 }).format(minor / 100) }
function apiError(err: any, fallback: string) { return err?.response?.data?.detail || fallback }
function setBusy(itemId: string, value: boolean) { busyItems.value = { ...busyItems.value, [itemId]: value } }
function recalculate(next: Cart): Cart { next.item_count = next.items.reduce((sum, item) => sum + item.quantity, 0); next.subtotal_minor = next.items.reduce((sum, item) => sum + item.line_total_minor, 0); return next }
async function reconcileCart() { try { cart.value = await cartState.load(storeSlug, true) } catch (err: any) { if (!cart.value) error.value = apiError(err, 'We could not load your cart.') } finally { loading.value = false } }
async function loadPaymentMethods() { loadingPaymentMethods.value = true; try { const response = await getPaymentMethods(storeSlug); paymentMethods.value = response.data; if (!selectedPaymentMethod.value && response.data.length) selectedPaymentMethod.value = response.data[0].public_id } catch (err: any) { error.value = apiError(err, 'We could not load the available payment methods.') } finally { loadingPaymentMethods.value = false } }
async function changeQuantity(itemId: string, quantity: number) { const current = cart.value; const item = current?.items.find(entry => entry.public_id === itemId); if (!current || !item || quantity < 1 || busyItems.value[itemId]) return; const previous = current; const optimistic = recalculate({ ...current, items: current.items.map(entry => entry.public_id === itemId ? { ...entry, quantity, line_total_minor: entry.unit_price_minor * quantity } : entry) }); cart.value = optimistic; cartState.update(storeSlug, optimistic); setBusy(itemId, true); error.value = ''; try { const response = await updateCartItem(storeSlug, itemId, quantity); cart.value = response.data; cartState.update(storeSlug, response.data) } catch (err: any) { cart.value = previous; cartState.update(storeSlug, previous); error.value = apiError(err, 'We could not update that item.') } finally { setBusy(itemId, false) } }
async function remove(itemId: string) { const current = cart.value; if (!current || busyItems.value[itemId]) return; const previous = current; const optimistic = recalculate({ ...current, items: current.items.filter(item => item.public_id !== itemId) }); cart.value = optimistic; cartState.update(storeSlug, optimistic); setBusy(itemId, true); error.value = ''; try { const response = await removeCartItem(storeSlug, itemId); cart.value = response.data; cartState.update(storeSlug, response.data) } catch (err: any) { cart.value = previous; cartState.update(storeSlug, previous); error.value = apiError(err, 'We could not remove that item.') } finally { setBusy(itemId, false) } }
function validateShipping() { fieldError.value = ''; if (!form.first_name.trim() || !form.last_name.trim() || !form.phone.trim()) { fieldError.value = 'Enter your first name, last name and phone number to continue.'; return false } return true }
function goToShipping() { if (!cart.value?.items.length) return; error.value = ''; if (validateShipping()) checkoutStep.value = 'shipping' }
function goToPayment() { fieldError.value = ''; error.value = ''; if (validateShipping()) { if (!selectedPaymentMethod.value) { fieldError.value = 'Choose a payment method to continue.'; return } checkoutStep.value = 'payment' } }
function paymentDescription(method: PaymentMethod) { if (method.code === 'mpesa') { if (method.payment_type === 'stk_push') return 'Pay with secure M-Pesa STK Push'; if (method.payment_type === 'till') return 'Pay via M-Pesa Till · Buy Goods and Services'; return 'Pay via M-Pesa Paybill' } if (method.code === 'cash') return 'Pay when your order is delivered or collected'; return 'Visa, Mastercard & compatible M-Pesa GlobalPay Visa cards' }
async function submitOrder() { if (!cart.value?.items.length || submitting.value || !selectedPaymentMethod.value) return; fieldError.value = ''; error.value = ''; submitting.value = true; try { order.value = (await checkoutCart(storeSlug, { first_name: form.first_name.trim(), last_name: form.last_name.trim(), phone: form.phone.trim(), email: form.email.trim() || undefined, notes: form.notes.trim() || undefined, payment_method_public_id: selectedPaymentMethod.value })).data; storeName.value = order.value.store_name || storeName.value; cart.value = null; cartState.clear(storeSlug) } catch (err: any) { error.value = apiError(err, 'We could not place your order. Please try again.'); await reconcileCart() } finally { submitting.value = false } }
async function refreshPaymentStatus() { if (!order.value?.tracking_url || order.value.payment?.status !== 'processing') return; try { const token = order.value.tracking_url.split('/').pop() || ''; const response = await getOrderTracking(storeSlug, token); if (response.data.payment) order.value.payment = response.data.payment } catch { /* tracking page remains available */ } }
onMounted(async () => { try { const [storeResponse] = await Promise.all([getStorefront(storeSlug), reconcileCart(), loadPaymentMethods()]); storeName.value = storeResponse.data.name; document.title = `Cart · ${storeName.value}` } catch (err: any) { if (!storeName.value) storeName.value = ''; if (!cart.value) error.value = apiError(err, 'We could not load this store.'); loading.value = false } })
</script>

<template>
  <main class="storefront-page">
    <header class="storefront-header"><RouterLink :to="`/${storeSlug}`" class="storefront-brand storefront-brand-link"><span class="storefront-mark">{{ storeName ? storeName.charAt(0).toUpperCase() : 'S' }}</span><div><strong>{{ storeName || 'Your store' }}</strong><small>Powered by DukaMe</small></div></RouterLink><RouterLink :to="`/${storeSlug}`" class="storefront-cart storefront-cart-link">Continue shopping</RouterLink></header>
    <section class="storefront-cart-page">
      <div v-if="loading" class="storefront-state"><div class="status-spinner" /><p>Loading your cart…</p></div>
      <div v-else-if="order" class="storefront-order-success"><div class="storefront-success-icon">✓</div><span class="storefront-eyebrow">Order received</span><h1>Thank you, {{ order.customer_first_name }}.</h1><p>Your order <strong>#{{ order.order_number }}</strong> has been received. We'll keep you updated as the store processes it.</p><div class="storefront-success-summary"><div><span>Payment</span><strong>{{ order.payment?.status === 'paid' ? 'Paid' : order.payment?.status === 'processing' ? 'Payment pending' : order.payment?.status === 'failed' ? 'Payment failed' : 'Payment pending' }}</strong></div><div><span>Total</span><strong>{{ money(order.total_minor, order.currency) }}</strong></div><div><span>Items</span><strong>{{ order.items.reduce((sum, item) => sum + item.quantity, 0) }}</strong></div></div><div v-if="paymentMessage" class="storefront-payment-result" :class="`is-${order.payment?.status || 'pending'}`"><strong>{{ order.payment?.method.name }}</strong><p>{{ paymentMessage }}</p><button v-if="order.payment?.status === 'processing'" type="button" @click="refreshPaymentStatus">Check payment status</button></div><div class="storefront-success-actions"><RouterLink v-if="trackingPath" :to="trackingPath" class="button button-primary button-lg">Track my order</RouterLink><RouterLink :to="`/${storeSlug}`" class="button button-secondary">Continue shopping</RouterLink></div><p class="storefront-success-notice">Your tracking page will show payment confirmation and order progress.</p></div>
      <template v-else-if="cart">
        <div class="storefront-cart-heading"><div><RouterLink :to="`/${storeSlug}`" class="storefront-back">← Continue shopping</RouterLink><h1>{{ checkoutStep === 'cart' ? 'Your cart' : checkoutStep === 'shipping' ? 'Delivery details' : 'Payment' }}</h1><p>{{ checkoutStep === 'cart' ? itemCountLabel : checkoutStep === 'shipping' ? 'Where should we contact you about this order?' : 'Choose how you want to pay.' }}</p></div><div v-if="cart.items.length" class="storefront-cart-heading-total"><span>Total</span><strong>{{ money(cart.subtotal_minor, cart.currency) }}</strong></div></div>
        <div v-if="cart.items.length" class="storefront-checkout-progress" aria-label="Checkout progress"><div class="storefront-checkout-step" :class="{ active: checkoutStep === 'cart', complete: checkoutStep !== 'cart' }"><span>1</span>Cart</div><div class="storefront-checkout-step" :class="{ active: checkoutStep === 'shipping', complete: checkoutStep === 'payment' }"><span>2</span>Details</div><div class="storefront-checkout-step" :class="{ active: checkoutStep === 'payment' }"><span>3</span>Payment</div></div>
        <div v-if="error" class="storefront-inline-error" role="alert">{{ error }}</div>
        <div v-if="checkoutStep === 'cart'" class="storefront-cart-layout">
          <section class="storefront-cart-items" aria-label="Cart items"><article v-for="item in cart.items" :key="item.public_id" class="storefront-cart-item" :class="{ 'is-busy': busyItems[item.public_id] }"><RouterLink :to="`/${storeSlug}/products/${item.product_slug}`" class="storefront-cart-item-image"><img v-if="item.image_url" :src="item.image_url" :alt="item.product_name" /><span v-else>No image</span></RouterLink><div class="storefront-cart-item-copy"><div class="storefront-cart-item-title"><RouterLink :to="`/${storeSlug}/products/${item.product_slug}`"><strong>{{ item.product_name }}</strong></RouterLink><button type="button" class="storefront-remove" :disabled="busyItems[item.public_id]" @click="remove(item.public_id)">Remove</button></div><small v-if="item.variant_label">{{ item.variant_label }}</small><small v-if="item.sku" class="storefront-item-sku">SKU: {{ item.sku }}</small><div class="storefront-cart-item-bottom"><div class="storefront-quantity" :class="{ disabled: busyItems[item.public_id] }"><button type="button" aria-label="Decrease quantity" :disabled="item.quantity <= 1 || busyItems[item.public_id]" @click="changeQuantity(item.public_id, item.quantity - 1)">−</button><span aria-live="polite">{{ item.quantity }}</span><button type="button" aria-label="Increase quantity" :disabled="busyItems[item.public_id]" @click="changeQuantity(item.public_id, item.quantity + 1)">+</button></div><div class="storefront-cart-item-price"><span>{{ money(item.unit_price_minor, item.currency) }} each</span><strong>{{ money(item.line_total_minor, item.currency) }}</strong></div></div></div></article></section>
          <aside class="storefront-checkout-card"><div class="storefront-checkout-title"><strong>Order summary</strong><span>{{ itemCountLabel }}</span></div><div class="storefront-order-total"><span>Subtotal</span><strong>{{ money(cart.subtotal_minor, cart.currency) }}</strong></div><p class="storefront-checkout-note">Shipping or delivery charges, if configured by the store, will be confirmed before payment.</p><button class="button button-primary button-lg storefront-add" type="button" @click="goToShipping">Proceed to checkout</button></aside>
        </div>
        <section v-else-if="checkoutStep === 'shipping'" class="storefront-checkout-panel"><h2>Enter your details</h2><p>We need these details to contact you and process your order.</p><div class="storefront-form-grid"><label><span>First name</span><input v-model="form.first_name" autocomplete="given-name" /></label><label><span>Last name</span><input v-model="form.last_name" autocomplete="family-name" /></label><label><span>Phone</span><input v-model="form.phone" type="tel" autocomplete="tel" placeholder="07xx xxx xxx" /></label><label><span>Email <em>Optional</em></span><input v-model="form.email" type="email" autocomplete="email" /></label><label class="storefront-form-full"><span>Order note <em>Optional</em></span><textarea v-model="form.notes" rows="3" placeholder="Delivery instructions or anything the store should know"></textarea></label></div><p v-if="fieldError" class="storefront-form-error">{{ fieldError }}</p><div class="storefront-checkout-actions"><button class="button button-secondary" type="button" @click="checkoutStep = 'cart'">Back to cart</button><button class="button button-primary button-lg" type="button" @click="goToPayment">Continue to payment</button></div></section>
        <section v-else class="storefront-checkout-panel"><h2>Choose payment</h2><p>Select one of the payment methods available for this store.</p><div class="storefront-checkout-summary"><span>Order total</span><strong>{{ money(cart.subtotal_minor, cart.currency) }}</strong></div><div v-if="loadingPaymentMethods" class="storefront-payment-loading">Loading payment options…</div><div v-else-if="paymentMethods.length" class="storefront-payment-options"><label v-for="method in paymentMethods" :key="method.public_id" class="storefront-payment-option" :class="[{ selected: selectedPaymentMethod === method.public_id }, `is-${method.code}`]"><input v-model="selectedPaymentMethod" type="radio" name="payment_method" :value="method.public_id" /><span class="storefront-payment-radio" aria-hidden="true"></span><span class="storefront-payment-copy"><strong>{{ method.name }}</strong><small>{{ paymentDescription(method) }}</small></span><span v-if="method.code === 'mpesa' && method.payment_type === 'stk_push'" class="storefront-payment-tag">Recommended</span><span v-if="method.code === 'card'" class="storefront-payment-brands"><span class="storefront-payment-brand">VISA</span><span class="storefront-payment-brand">MC</span></span></label></div><p v-else class="storefront-form-error">No payment methods are currently available.</p><p v-if="selectedMethod?.instructions" class="storefront-checkout-note">{{ selectedMethod.instructions }}</p><p v-if="fieldError" class="storefront-form-error">{{ fieldError }}</p><div class="storefront-checkout-actions"><button class="button button-secondary" type="button" @click="checkoutStep = 'shipping'">Back to details</button><button class="button button-primary button-lg" type="button" :disabled="submitting || loadingPaymentMethods || !paymentMethods.length" @click="submitOrder">{{ submitting ? 'Placing order…' : `Place order · ${money(cart.subtotal_minor, cart.currency)}` }}</button></div><div class="storefront-secure-note"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><rect x="5" y="10" width="14" height="10" rx="2" /><path d="M8 10V7a4 4 0 0 1 8 0v3" /></svg>Secure payment · Never share your M-Pesa PIN with anyone</div></section>
        <div v-if="!cart.items.length" class="storefront-empty storefront-cart-empty"><div class="storefront-empty-icon" aria-hidden="true">—</div><h2>Your cart is empty</h2><p>Add a product to your cart and it will appear here.</p><RouterLink :to="`/${storeSlug}`" class="button button-primary">Browse products</RouterLink></div>
      </template>
    </section>
  </main>
</template>
