<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { createPaymentMethod, getPaymentMethodsForTenant, getPayments, markCashPaymentPaid, markManualPaymentPaid, retryPayment, testPaymentMethod, updatePaymentMethod, type PaymentListItem, type PaymentMethod } from '../lib/cart'
import { useAuthStore } from '../stores/auth'
import { APP_NAME } from '../lib/branding'

const props = defineProps<{ settingsOnly?: boolean }>()
const auth = useAuthStore()
const methods = ref<PaymentMethod[]>([])
const payments = ref<PaymentListItem[]>([])
const loading = ref(true)
const saving = ref(false)
const testing = ref(false)
const error = ref('')
const success = ref('')
const showMpesaForm = ref(false)
const showStkForm = ref(false)
const defaultAccountReference = `${APP_NAME} Order`.slice(0, 12)
const defaultTransactionDesc = `${APP_NAME} Pay`.slice(0, 13)

const manualForm = reactive({ name: 'M-Pesa', payment_type: 'paybill' as 'paybill' | 'till', number: '', account_mode: 'order_number' as 'order_number' | 'customer_reference' | 'fixed', account_reference: '', instructions: '' })
const stkForm = reactive({ name: 'M-Pesa STK Push', consumer_key: '', consumer_secret: '', shortcode: '', passkey: '', environment: 'sandbox' as 'sandbox' | 'production', transaction_type: 'CustomerPayBillOnline' as 'CustomerPayBillOnline' | 'CustomerBuyGoodsOnline', account_reference: defaultAccountReference, transaction_desc: defaultTransactionDesc })

const tenantId = computed(() => auth.activeTenant?.public_id || '')
const manualMpesaMethod = computed(() => methods.value.find(method => method.code === 'mpesa' && method.payment_type !== 'stk_push'))
const stkMethod = computed(() => methods.value.find(method => method.code === 'mpesa' && method.payment_type === 'stk_push'))
const hasCard = computed(() => methods.value.some(method => method.code === 'card'))
const manualTypeLabel = computed(() => manualForm.payment_type === 'paybill' ? 'Paybill' : 'Till Number')

function apiError(err: any, fallback: string) { return err?.response?.data?.detail || fallback }
function money(amount: number, currency: string) { return `${currency} ${(amount / 100).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` }
function statusLabel(status: string) { return status.replaceAll('_', ' ').replace(/\b\w/g, value => value.toUpperCase()) }
function openManualForm() { error.value = ''; success.value = ''; const method = manualMpesaMethod.value; manualForm.name = method?.name || 'M-Pesa'; manualForm.payment_type = method?.payment_type === 'till' ? 'till' : 'paybill'; manualForm.number = ''; manualForm.account_mode = 'order_number'; manualForm.account_reference = ''; manualForm.instructions = method?.instructions || ''; showMpesaForm.value = true }
function openStkForm() { error.value = ''; success.value = ''; const method = stkMethod.value; stkForm.name = method?.name || 'M-Pesa STK Push'; stkForm.consumer_key = ''; stkForm.consumer_secret = ''; stkForm.shortcode = ''; stkForm.passkey = ''; stkForm.environment = 'sandbox'; stkForm.transaction_type = 'CustomerPayBillOnline'; stkForm.account_reference = defaultAccountReference; stkForm.transaction_desc = defaultTransactionDesc; showStkForm.value = true }
async function load() { if (!tenantId.value) return; loading.value = true; error.value = ''; try { methods.value = (await getPaymentMethodsForTenant(tenantId.value)).data; if (!props.settingsOnly) payments.value = (await getPayments(tenantId.value, { limit: 50 })).data } catch (err: any) { error.value = apiError(err, 'We could not load payment information.') } finally { loading.value = false } }
async function saveManual() { if (!tenantId.value || saving.value) return; error.value = ''; success.value = ''; const number = manualForm.number.trim(); if (!/^\d{5,8}$/.test(number)) { error.value = `Enter a valid 5–8 digit M-Pesa ${manualTypeLabel.value}.`; return } if (manualForm.payment_type === 'paybill' && manualForm.account_mode === 'fixed' && !manualForm.account_reference.trim()) { error.value = 'Enter the fixed account reference customers should use.'; return } saving.value = true; try { const config = { payment_type: manualForm.payment_type, paybill_number: manualForm.payment_type === 'paybill' ? number : '', till_number: manualForm.payment_type === 'till' ? number : '', account_mode: manualForm.payment_type === 'till' ? 'none' : manualForm.account_mode, account_reference: manualForm.payment_type === 'till' ? '' : manualForm.account_reference.trim() }; const payload = { name: manualForm.name.trim() || 'M-Pesa', instructions: manualForm.instructions.trim() || undefined, is_enabled: true, config }; const response = manualMpesaMethod.value ? await updatePaymentMethod(tenantId.value, manualMpesaMethod.value.public_id, payload) : await createPaymentMethod(tenantId.value, { code: 'mpesa_paybill', ...payload }); methods.value = manualMpesaMethod.value ? methods.value.map(item => item.public_id === response.data.public_id ? response.data : item) : [...methods.value, response.data]; success.value = `${manualTypeLabel.value} is ready for checkout.`; showMpesaForm.value = false } catch (err: any) { error.value = apiError(err, 'We could not save the M-Pesa configuration.') } finally { saving.value = false } }
async function saveStk() { if (!tenantId.value || saving.value) return; error.value = ''; success.value = ''; if (!stkMethod.value && (!stkForm.consumer_key.trim() || !stkForm.consumer_secret.trim() || !stkForm.shortcode.trim() || !stkForm.passkey.trim())) { error.value = 'Enter the Consumer Key, Consumer Secret, Business Shortcode and Passkey.'; return } if (!/^\d{5,8}$/.test(stkForm.shortcode.trim())) { error.value = 'Enter a valid 5–8 digit Business Shortcode.'; return } if (!stkForm.account_reference.trim()) { error.value = 'Enter the account reference shown to customers.'; return } if (stkForm.account_reference.trim().length > 12) { error.value = 'Account reference must be 12 characters or fewer.'; return } if (stkForm.transaction_desc.trim().length > 13) { error.value = 'Transaction description must be 13 characters or fewer.'; return } saving.value = true; try { const config: Record<string, string> = { environment: stkForm.environment, transaction_type: stkForm.transaction_type, account_reference: stkForm.account_reference.trim(), transaction_desc: stkForm.transaction_desc.trim() || defaultTransactionDesc }; if (stkForm.consumer_key.trim()) config.consumer_key = stkForm.consumer_key.trim(); if (stkForm.consumer_secret.trim()) config.consumer_secret = stkForm.consumer_secret.trim(); if (stkForm.shortcode.trim()) config.shortcode = stkForm.shortcode.trim(); if (stkForm.passkey.trim()) config.passkey = stkForm.passkey.trim(); const payload = { name: stkForm.name.trim() || 'M-Pesa STK Push', instructions: 'Customers enter their M-Pesa phone number at checkout and receive a secure STK Push on their phone.', is_enabled: true, config }; const response = stkMethod.value ? await updatePaymentMethod(tenantId.value, stkMethod.value.public_id, payload) : await createPaymentMethod(tenantId.value, { code: 'mpesa', ...payload }); methods.value = stkMethod.value ? methods.value.map(item => item.public_id === response.data.public_id ? response.data : item) : [...methods.value, response.data]; success.value = 'M-Pesa STK Push is configured. Test the connection before using it in production.'; showStkForm.value = false } catch (err: any) { error.value = apiError(err, 'We could not save the Daraja configuration.') } finally { saving.value = false } }
async function testStk() { if (!tenantId.value || !stkMethod.value || testing.value) return; testing.value = true; error.value = ''; success.value = ''; try { const response = await testPaymentMethod(tenantId.value, stkMethod.value.public_id); success.value = response.data.message } catch (err: any) { error.value = apiError(err, 'M-Pesa connection test failed.') } finally { testing.value = false } }
async function addCard() { if (!tenantId.value || saving.value || hasCard.value) return; saving.value = true; error.value = ''; success.value = ''; try { const response = await createPaymentMethod(tenantId.value, { code: 'card', name: 'Card', is_enabled: true, instructions: 'Secure card payment through the configured card provider. Visa, Mastercard and compatible M-Pesa GlobalPay Visa cards can be used.' }); methods.value = [...methods.value, response.data]; success.value = 'Card payments are enabled.' } catch (err: any) { error.value = apiError(err, 'We could not enable card payments.') } finally { saving.value = false } }
async function toggleMethod(method: PaymentMethod) { if (!tenantId.value || saving.value) return; saving.value = true; error.value = ''; success.value = ''; try { const response = await updatePaymentMethod(tenantId.value, method.public_id, { is_enabled: !method.is_enabled }); methods.value = methods.value.map(item => item.public_id === method.public_id ? response.data : item); success.value = `${method.name} ${response.data.is_enabled ? 'enabled' : 'disabled'}.` } catch (err: any) { error.value = apiError(err, 'We could not update the payment method.') } finally { saving.value = false } }
async function settle(payment: PaymentListItem) { if (!tenantId.value || saving.value) return; saving.value = true; error.value = ''; success.value = ''; try { if (payment.method.code === 'cash') await markCashPaymentPaid(tenantId.value, payment.public_id); else await markManualPaymentPaid(tenantId.value, payment.public_id); success.value = `Payment for ${payment.order_number} marked as paid.`; await load() } catch (err: any) { error.value = apiError(err, 'We could not settle the payment.') } finally { saving.value = false } }
async function retryMpesa(payment: PaymentListItem) { if (!tenantId.value || saving.value) return; saving.value = true; error.value = ''; success.value = ''; try { await retryPayment(tenantId.value, payment.public_id); success.value = 'A new M-Pesa payment prompt has been sent.'; await load() } catch (err: any) { error.value = apiError(err, 'We could not retry the M-Pesa payment.') } finally { saving.value = false } }
function methodDescription(method: PaymentMethod) { if (method.code === 'mpesa') { if (method.payment_type === 'stk_push') return 'Daraja STK Push · automated M-Pesa prompt'; if (method.payment_type === 'till') return 'M-Pesa Till · Buy Goods and Services'; return 'M-Pesa Paybill · manual confirmation' } if (method.code === 'card') return 'Secure card checkout or configured processor'; return method.instructions || 'Pay in cash when the order is delivered or collected.' }
function isManualMpesa(method: PaymentMethod) { return method.code === 'mpesa' && method.payment_type !== 'stk_push' }
onMounted(load)
</script>

<template>
  <section class="page payments-page">
    <div class="page-header"><div><span class="page-eyebrow">{{ settingsOnly ? 'Settings' : 'Commerce' }}</span><h1>{{ settingsOnly ? 'Payment settings' : 'Payments' }}</h1><p>{{ settingsOnly ? 'Connect the payment methods your customers can use at checkout.' : 'Review payment activity and settlement status.' }}</p></div></div>
    <div v-if="error" class="commerce-error">{{ error }}</div><div v-if="success" class="commerce-success">{{ success }}</div>
    <div v-if="loading" class="commerce-state"><div class="status-spinner" /><p>Loading payments…</p></div>
    <template v-else>
      <section v-if="settingsOnly" class="payments-methods-card"><div class="payments-card-head"><div><h2>M-Pesa</h2><p>Offer manual Paybill/Till payments or automate checkout with Daraja STK Push.</p></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="button button-secondary" type="button" :disabled="saving" @click="openManualForm">{{ manualMpesaMethod ? 'Configure Paybill / Till' : 'Add Paybill / Till' }}</button><button class="button button-primary" type="button" :disabled="saving" @click="openStkForm">{{ stkMethod ? 'Configure STK Push' : 'Connect STK Push' }}</button><button v-if="stkMethod" class="button button-secondary" type="button" :disabled="testing" @click="testStk">{{ testing ? 'Testing…' : 'Test connection' }}</button></div></div><div class="payments-method-list"><article v-for="method in methods.filter(item => item.code === 'mpesa')" :key="method.public_id" class="payments-method-row"><div class="payments-method-icon">M</div><div class="payments-method-copy"><strong>{{ method.name }}</strong><span>{{ methodDescription(method) }}</span></div><span class="payments-enabled">{{ method.is_enabled ? 'Enabled' : 'Disabled' }}</span><button class="button button-secondary" type="button" :disabled="saving" @click="toggleMethod(method)">{{ method.is_enabled ? 'Disable' : 'Enable' }}</button></article></div></section>

      <section v-if="settingsOnly && showStkForm" class="payments-config-card"><div class="payments-card-head"><div><h2>Daraja STK Push</h2><p>Connect your Safaricom Daraja application. Credentials are encrypted before storage and are never sent to the storefront.</p></div></div><div class="payments-form-grid"><label><span>Environment</span><select v-model="stkForm.environment"><option value="sandbox">Sandbox</option><option value="production">Production</option></select></label><label><span>Transaction type</span><select v-model="stkForm.transaction_type"><option value="CustomerPayBillOnline">PayBill</option><option value="CustomerBuyGoodsOnline">Buy Goods</option></select></label><label><span>Consumer Key</span><input v-model="stkForm.consumer_key" type="password" autocomplete="off" placeholder="Daraja Consumer Key" /></label><label><span>Consumer Secret</span><input v-model="stkForm.consumer_secret" type="password" autocomplete="off" placeholder="Daraja Consumer Secret" /></label><label><span>Business Shortcode</span><input v-model="stkForm.shortcode" inputmode="numeric" maxlength="8" placeholder="e.g. 174379" /></label><label><span>Passkey</span><input v-model="stkForm.passkey" type="password" autocomplete="off" placeholder="LNM/STK Passkey" /></label><label><span>Account reference</span><input v-model="stkForm.account_reference" maxlength="12" :placeholder="defaultAccountReference" /></label><label><span>Transaction description</span><input v-model="stkForm.transaction_desc" maxlength="13" :placeholder="defaultTransactionDesc" /></label><label><span>Display name</span><input v-model="stkForm.name" maxlength="100" /></label><label class="payments-form-full"><span>Checkout behaviour</span><p class="payments-checkout-hint">Customer enters their Kenyan M-Pesa number → {{ APP_NAME }} sends the STK Push → customer enters their M-Pesa PIN on the phone → Daraja callback verifies the payment → the order is confirmed.</p></label><label class="payments-form-full"><span>Callback URL</span><input :value="stkMethod?.callback_url || 'Generated automatically after saving'" readonly /></label></div><div class="payments-config-actions"><button class="button button-secondary" type="button" :disabled="saving" @click="showStkForm = false">Cancel</button><button class="button button-primary" type="button" :disabled="saving" @click="saveStk">{{ saving ? 'Saving…' : 'Save STK Push' }}</button></div></section>

      <section v-if="settingsOnly && showMpesaForm" class="payments-config-card"><div class="payments-card-head"><div><h2>Manual M-Pesa</h2><p>Use your existing Paybill or Till. This does not use Daraja credentials.</p></div></div><div class="payments-form-grid"><label><span>Payment type</span><select v-model="manualForm.payment_type"><option value="paybill">Paybill</option><option value="till">Till Number</option></select></label><label><span>{{ manualForm.payment_type === 'paybill' ? 'Paybill number' : 'Till Number' }}</span><input v-model="manualForm.number" inputmode="numeric" maxlength="8" /></label><label v-if="manualForm.payment_type === 'paybill'"><span>Customer account reference</span><select v-model="manualForm.account_mode"><option value="order_number">{{ APP_NAME }} order number</option><option value="customer_reference">Customer name/reference</option><option value="fixed">Fixed account/reference</option></select></label><label v-if="manualForm.payment_type === 'paybill' && manualForm.account_mode === 'fixed'"><span>Fixed account/reference</span><input v-model="manualForm.account_reference" maxlength="20" /></label><label><span>Display name</span><input v-model="manualForm.name" maxlength="100" /></label><label class="payments-form-full"><span>Checkout instructions <em>Optional</em></span><textarea v-model="manualForm.instructions" rows="3"></textarea></label></div><div class="payments-config-actions"><button class="button button-secondary" type="button" :disabled="saving" @click="showMpesaForm = false">Cancel</button><button class="button button-primary" type="button" :disabled="saving" @click="saveManual">{{ saving ? 'Saving…' : 'Save M-Pesa' }}</button></div></section>

      <section v-if="settingsOnly" class="payments-methods-card"><div class="payments-card-head"><div><h2>Other payment methods</h2><p>Cash is available by default. Card will be connected to a secure gateway in the next payment phase.</p></div><button v-if="!hasCard" class="button button-secondary" type="button" :disabled="saving" @click="addCard">Add Card</button></div><div class="payments-method-list"><article v-for="method in methods.filter(item => item.code !== 'mpesa')" :key="method.public_id" class="payments-method-row"><div class="payments-method-icon">{{ method.code === 'card' ? 'V' : 'C' }}</div><div class="payments-method-copy"><strong>{{ method.name }}</strong><span>{{ methodDescription(method) }}</span></div><span class="payments-enabled">{{ method.is_enabled ? 'Enabled' : 'Disabled' }}</span><button class="button button-secondary" type="button" :disabled="saving" @click="toggleMethod(method)">{{ method.is_enabled ? 'Disable' : 'Enable' }}</button></article></div></section>

      <section v-if="!settingsOnly" class="payments-methods-card"><div class="payments-card-head"><div><h2>Payment activity</h2><p>Recent payments across your store.</p></div></div><div v-if="!payments.length" class="commerce-state"><p>No payments yet.</p></div><div v-else class="payments-method-list"><article v-for="payment in payments" :key="payment.public_id" class="payments-method-row"><div class="payments-method-copy"><strong>{{ payment.order_number }} · {{ payment.customer_first_name }} {{ payment.customer_last_name }}</strong><span>{{ payment.method.name }} · {{ money(payment.amount_minor, payment.currency) }} · {{ payment.attempt_count }} attempt{{ payment.attempt_count === 1 ? '' : 's' }}</span></div><span class="payments-enabled">{{ statusLabel(payment.status) }}</span><button v-if="(payment.method.code === 'cash' || payment.method.code === 'card' || isManualMpesa(payment.method)) && payment.status !== 'paid'" class="button button-secondary" type="button" :disabled="saving" @click="settle(payment)">Mark paid</button><button v-else-if="payment.method.code === 'mpesa' && payment.method.payment_type === 'stk_push' && payment.status === 'failed'" class="button button-primary" type="button" :disabled="saving" @click="retryMpesa(payment)">Retry</button></article></div></section>
    </template>
  </section>
</template>
